apiVersion: v1
kind: Service
metadata:
  name: devops-assignment-service
spec:
  type: NodePort     # change to LoadBalancer if using cloud
  selector:
    app: devops-assignment
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
